language: node_js

install:
  - npm install

script:
  - npm run lint && npm run test

after_success:
  - "./node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
